name: Generate Snake Game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@master
        with:
          github_user_name: Tambi19
          outputs: dist/snake.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout output || git checkout -b output
          mv dist/snake.svg snake.svg
          git add snake.svg
          git commit -m "Generate snake animation" || echo "No changes to commit"
          git push origin output --force
